# Generated by Django 4.2.10 on 2026-04-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'ordering': ['price', 'billing_period']},
        ),
    ]
