# Generated by Django 4.2.10 on 2026-04-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_pricingplan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('business', 'Business')], max_length=20),
        ),
    ]
