# Generated by Django 4.2.10 on 2026-04-25 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_view', models.CharField(choices=[('grid', 'Grid View'), ('list', 'List View'), ('table', 'Table View')], default='table', max_length=20)),
                ('items_per_page', models.IntegerField(choices=[(10, 10), (25, 25), (50, 50), (100, 100)], default=10)),
                ('show_stats_widget', models.BooleanField(default=True)),
                ('show_recent_jobs_widget', models.BooleanField(default=True)),
                ('show_usage_chart', models.BooleanField(default=True)),
                ('show_notifications', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='light', max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('job_completion_notifications', models.BooleanField(default=True)),
                ('job_failure_notifications', models.BooleanField(default=True)),
                ('custom_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_upload_time', models.FloatField(default=0, help_text='Total upload time in seconds')),
                ('total_processing_time', models.FloatField(default=0, help_text='Total processing time in seconds')),
                ('total_downloads', models.IntegerField(default=0)),
                ('total_transcriptions', models.IntegerField(default=0)),
                ('total_translations', models.IntegerField(default=0)),
                ('total_subtitle_generations', models.IntegerField(default=0)),
                ('total_audio_generations', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('login_count', models.IntegerField(default=0)),
                ('average_session_time', models.FloatField(default=0, help_text='Average session time in minutes')),
                ('total_files_uploaded', models.IntegerField(default=0)),
                ('total_storage_used_mb', models.FloatField(default=0)),
                ('average_file_size_mb', models.FloatField(default=0)),
                ('most_used_source_language', models.CharField(blank=True, max_length=10, null=True)),
                ('most_used_target_language', models.CharField(blank=True, max_length=10, null=True)),
                ('last_export_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('job_created', 'Job Created'), ('job_completed', 'Job Completed'), ('job_failed', 'Job Failed'), ('file_uploaded', 'File Uploaded'), ('subscription_changed', 'Subscription Changed'), ('settings_updated', 'Settings Updated'), ('download', 'Download')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recent activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('job', 'Job'), ('transcript', 'Transcript'), ('translation', 'Translation'), ('subtitle', 'Subtitle File')], max_length=20)),
                ('item_id', models.UUIDField(help_text='ID of the referenced item')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'item_type', 'item_id')},
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('stats', 'Statistics'), ('chart', 'Chart'), ('recent_jobs', 'Recent Jobs'), ('quota', 'Quota Usage'), ('tips', 'Tips & Tricks'), ('custom', 'Custom')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('column', models.IntegerField(default=0, help_text='Column position (0-2)')),
                ('order', models.IntegerField(default=0, help_text='Order within column')),
                ('is_visible', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['column', 'order'],
                'unique_together': {('user', 'column', 'order')},
            },
        ),
    ]
