# Generated by Django 4.2.10 on 2026-04-25 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('job_type', models.CharField(choices=[('audio_to_text', 'Audio → Text'), ('video_to_text', 'Video → Text'), ('audio_to_audio', 'Audio → Audio Dubbing'), ('video_to_audio', 'Video → Audio Dubbing'), ('video_to_video', 'Video → Video Dubbing'), ('youtube_to_video', 'YouTube → Dubbed Video')], max_length=20)),
                ('output_types', models.JSONField(default=list, help_text='List of output types requested')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher = higher priority')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('source_language', models.CharField(default='lg', max_length=10)),
                ('target_language', models.CharField(default='en', max_length=10)),
                ('transcript', models.TextField(blank=True)),
                ('translation', models.TextField(blank=True)),
                ('subtitle_file', models.FileField(blank=True, null=True, upload_to='subtitles/%Y/%m/%d/')),
                ('dubbed_audio', models.FileField(blank=True, null=True, upload_to='dubbed_audio/%Y/%m/%d/')),
                ('dubbed_video', models.FileField(blank=True, null=True, upload_to='dubbed_video/%Y/%m/%d/')),
                ('voice_model', models.CharField(blank=True, help_text='Voice model to use for TTS', max_length=100, null=True)),
                ('add_background_music', models.BooleanField(default=False)),
                ('background_music_file', models.FileField(blank=True, null=True, upload_to='background_music/')),
                ('music_volume', models.FloatField(default=0.3, help_text='Background music volume (0-1)')),
                ('preserve_timestamps', models.BooleanField(default=True, help_text='Preserve original timing in dubbed output')),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='jobs_job_user_id_ec4047_idx'), models.Index(fields=['status', 'priority'], name='jobs_job_status_007c84_idx'), models.Index(fields=['created_at'], name='jobs_job_created_1b3a4d_idx'), models.Index(fields=['job_type'], name='jobs_job_job_typ_f6c220_idx')],
            },
        ),
    ]
