# Generated by Django 5.2.13 on 2026-04-23 21:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('job_type', models.CharField(choices=[('audio', 'Audio File'), ('video', 'Video File'), ('youtube', 'YouTube URL')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('source_language', models.CharField(default='lg', max_length=10)),
                ('target_language', models.CharField(default='en', max_length=10)),
                ('transcript', models.TextField(blank=True)),
                ('translation', models.TextField(blank=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
