# Generated by Django 4.2.10 on 2026-04-27 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('text_to_text', 'Text → Text'), ('audio_to_text', 'Audio → Text'), ('video_to_text', 'Video → Text'), ('audio_to_audio', 'Audio → Audio Dubbing'), ('video_to_audio', 'Video → Audio Dubbing'), ('video_to_video', 'Video → Video Dubbing'), ('youtube_to_video', 'YouTube → Dubbed Video')], max_length=20),
        ),
        migrations.CreateModel(
            name='FailedTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(help_text='Celery task ID', max_length=255, unique=True)),
                ('task_name', models.CharField(help_text='Name of the Celery task', max_length=255)),
                ('error', models.TextField(help_text='Error message')),
                ('traceback', models.TextField(blank=True, help_text='Full traceback')),
                ('retry_count', models.IntegerField(default=0)),
                ('resolved', models.BooleanField(default=False, help_text='Whether the issue has been resolved')),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_tasks', to='jobs.job')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Failed Task',
                'verbose_name_plural': 'Failed Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
