# Generated by Django 4.2.10 on 2026-04-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_job_type_failedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='source_text',
            field=models.TextField(blank=True, help_text='Source text for text-to-text translation'),
        ),
    ]
